# Generated by Django 5.0.6 on 2026-05-14 00:51

import core.enums.mission_enums
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('mission_type', models.CharField(choices=[('FLOOD_MONITORING', 'FLOOD_MONITORING'), ('COASTAL_PATROL', 'COASTAL_PATROL'), ('EMERGENCY_DELIVERY', 'EMERGENCY_DELIVERY'), ('TRAFFIC_SURVEILLANCE', 'TRAFFIC_SURVEILLANCE'), ('ENVIRONMENTAL_MONITORING', 'ENVIRONMENTAL_MONITORING')], max_length=40)),
                ('region', models.CharField(choices=[('Centro', 'Centro'), ('Itaipuaçu', 'Itaipuaçu'), ('Ponta Negra', 'Ponta Negra'), ('Inoã', 'Inoã'), ('São José', 'São José'), ('Cordeirinho', 'Cordeirinho')], max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=core.enums.mission_enums.MissionPriority['MEDIUM'], max_length=20)),
                ('route_strategy', models.CharField(choices=[('FASTEST', 'FASTEST'), ('SAFE', 'SAFE'), ('BATTERY_SAVING', 'BATTERY_SAVING')], default=core.enums.mission_enums.RouteStrategyType['FASTEST'], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('ABORTED', 'ABORTED')], default=core.enums.mission_enums.MissionStatus['PENDING'], max_length=20)),
                ('estimated_duration_min', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('battery_consumption_pct', models.FloatField(blank=True, null=True)),
                ('weather_risk_score', models.FloatField(blank=True, null=True)),
                ('waypoints', models.JSONField(default=list)),
                ('route_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='drones.drone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOW_BATTERY', 'LOW_BATTERY'), ('BAD_WEATHER', 'BAD_WEATHER'), ('SIGNAL_LOST', 'SIGNAL_LOST'), ('MISSION_STARTED', 'MISSION_STARTED'), ('MISSION_COMPLETED', 'MISSION_COMPLETED'), ('RETURN_TO_BASE', 'RETURN_TO_BASE'), ('OBSTACLE_DETECTED', 'OBSTACLE_DETECTED'), ('MISSION_FAILED', 'MISSION_FAILED')], max_length=30)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='INFO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='missions.mission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
